 def _tab_runner(self, root):
        top = ttk.Frame(root); top.pack(fill="x")
        self.run_folder = tk.StringVar(value=os.path.join(Path.cwd(), "/sharc/campaigns"))
        ttk.Label(top, text="Pasta com arquivos .yaml").pack(side="left")
        e = ttk.Entry(top, textvariable=self.run_folder)
        e.pack(side="left", fill="x", expand=True, padx=6)
        ttk.Button(top, text="Escolher...", command=lambda: self._pick_folder(self.run_folder)).pack(side="left")
        ttk.Button(top, text="Atualizar lista", command=self._scan_yaml_files).pack(side="left", padx=(6,0))
        ttk.Label(top, text="Paralelo (máx execuções):").pack(side="left", padx=(14,4))
        tk.Spinbox(top, from_=1, to=32, width=4, textvariable=self.var_max_workers).pack(side="left")

        # Tree for files + progress
        mid = ttk.Frame(root); mid.pack(fill="both", expand=True, pady=(8,0))
        self.tree = ttk.Treeview(mid, columns=("yaml","status","snap","pct","eta"), show="headings", height=12)
        self.tree.heading("yaml", text="YAML")
        self.tree.heading("status", text="Status")
        self.tree.heading("snap", text="Snapshots (done/total)")
        self.tree.heading("pct", text="%")
        self.tree.heading("eta", text="ETA")
        self.tree.column("yaml", width=380)
        self.tree.column("status", width=220)
        self.tree.column("snap", width=180)
        self.tree.column("pct", width=60, anchor="e")
        self.tree.column("eta", width=120)
        self.tree.pack(side="left", fill="both", expand=True)
        sb = ttk.Scrollbar(mid, orient="vertical", command=self.tree.yview); sb.pack(side="left", fill="y")
        self.tree.configure(yscroll=sb.set)

        right = ttk.Frame(root); right.pack(fill="x", pady=(8,0))
        self.main_cli_path = tk.StringVar(value=os.path.join(os.path.dirname(os.path.abspath(__file__)), "main_cli.py"))
        ttk.Label(right, text="main_cli.py:").pack(side="left")
        ttk.Entry(right, textvariable=self.main_cli_path, width=44).pack(side="left", padx=6, fill="x", expand=True)
        ttk.Button(right, text="Parar selecionados", command=self._stop_selected).pack(side="right", padx=(6,0))
        ttk.Button(right, text="Executar selecionados", command=self._run_selected_yaml_parallel).pack(side="right")

        logf = ttk.LabelFrame(root, text="Log")
        logf.pack(fill="both", expand=True, pady=(8,0))
        self.txt_log = tk.Text(logf, height=10, wrap="none")
        self.txt_log.pack(fill="both", expand=True)

        self._scan_yaml_files()
        self.after(150, self._drain_log_queue)
        self.after(250, self._runner_scheduler_tick)