---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(message)s"
    detailed:
        class: logging.Formatter
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        formatter: detailed
        stream: ext://sys.stdout

    file:
        class: logging.handlers.RotatingFileHandler
        formatter: simple
        filename: output/logfile.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: INFO
    handlers: [console, file]
